linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  goconst:
    min-len: 2
    min-occurrences: 3
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
  govet:
    check-shadowing: true
    enable:
      - assign
      - bools
      - httpresponse
      - lostcancel
      - stdmethods
      - stringintconv
  nolintlint:
    require-explanation: true
    require-specific: true
linters:
  disable-all: true
  enable:
    - errcheck
    - govet
    - gofmt
    - unused
    - typecheck
    - gosimple
    - ineffassign
    - sqlclosecheck
    # - bodyclose
    # - depguard
    # - dogsled
    # - dupl
    # - exportloopref
    # - exhaustive
    # - goconst
    # - gocritic
    # - goimports
    # - gomnd
    # - gocyclo
    # - gosec
    # - misspell
    # - nolintlint
    # - nakedret
    # - prealloc
    # - predeclared
    # - revive
    # - staticcheck
    # - stylecheck
    # - thelper
    # - tparallel
    # - unconvert
    # - unparam
    # - varcheck
    # - whitespace
    # - wsl

run:
  issues-exit-code: 1
issues:
  exclude-rules:
    # Excluding err shadowing as second return value
    - text: 'shadow: declaration of "(err|ctx)" shadows declaration at'
      linters:
        - govet
