// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package sqlc

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type AuthToken struct {
	ID        uuid.UUID
	ExpiresAt time.Time
	CreatedAt time.Time
}

type User struct {
	UserID       int64
	FirstName    string
	LastName     sql.NullString
	TgUsername   sql.NullString
	LanguageCode sql.NullString
	TgPhotoUrl   sql.NullString
	TgPremium    bool
	RoleID       int32
	OnlineAt     time.Time
	UpdatedAt    time.Time
	CreatedAt    time.Time
}

type UserFavorite struct {
	UserID    int64
	ProductID int64
	CreatedAt time.Time
}

type UserRole struct {
	RoleID   int32
	RoleName string
}
