// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: queries.sql

package sqlc

import (
	"context"
)

const getUserRole = `-- name: GetUserRole :one
SELECT ur.role_name FROM users u INNER JOIN user_role ur ON u.role_id = ur.role_id WHERE u.user_id = $1
`

func (q *Queries) GetUserRole(ctx context.Context, userID int64) (string, error) {
	row := q.db.QueryRow(ctx, getUserRole, userID)
	var role_name string
	err := row.Scan(&role_name)
	return role_name, err
}
