// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	DeleteRefreshToken(ctx context.Context, id uuid.UUID) (int64, error)
	GetUserRole(ctx context.Context, userID int64) (string, error)
	SaveRefreshToken(ctx context.Context, arg SaveRefreshTokenParams) error
}

var _ Querier = (*Queries)(nil)
