query UserSoundtracks($id: ID!, $page: Int!) {
  userSoundtracks(id: $id, filter: { page: $page }) {
    __typename
    ... on UserSoundtracksResponse {
      total
      soundtracks {
        id
        title
        author
        duration
        coverURL
        audioURL
        attached
      }
    }
    ... on NotFound {
      message
    }
  }
}
