// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package sqlc

import (
	"database/sql"
	"time"
)

type Soundtrack struct {
	ID         int64
	Title      string
	Author     string
	Duration   int16
	CoverImage sql.NullString
	AudioFile  string
	CreatorID  int64
	UpdatedAt  time.Time
	CreatedAt  time.Time
}

type SoundtrackHash struct {
	ID           int64
	Hash         string
	SoundtrackID int64
}
