// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package sqlc

import (
	"context"
)

type Querier interface {
	CreateSoundtrack(ctx context.Context, arg CreateSoundtrackParams) (int64, error)
	DeleteSoundtrack(ctx context.Context, id int64) (int64, error)
	GetSoundtrack(ctx context.Context, arg GetSoundtrackParams) (GetSoundtrackRow, error)
	SaveSoundtrackHash(ctx context.Context, arg SaveSoundtrackHashParams) error
}

var _ Querier = (*Queries)(nil)
