// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: queries.sql

package sqlc

import (
	"context"
)

const getSoundtrack = `-- name: GetSoundtrack :one


SELECT id, title, author, duration, cover_image, audio_file, creator_id, updated_at, created_at FROM soundtrack WHERE id = $1
`

// -- name: GetSoundtrack :one
// SELECT *, EXISTS
//
//	(SELECT TRUE FROM user_soundtrack WHERE soundtrack_id = id AND user_soundtrack.user_id = $2) AS attached
//
// FROM soundtrack WHERE id = $1;
func (q *Queries) GetSoundtrack(ctx context.Context, id int64) (Soundtrack, error) {
	row := q.db.QueryRow(ctx, getSoundtrack, id)
	var i Soundtrack
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Author,
		&i.Duration,
		&i.CoverImage,
		&i.AudioFile,
		&i.CreatorID,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}
