query Soundtracks($first: Int!, $after: String) {
  soundtracks(first: $first, after: $after) {
    totalCount
    pageInfo {
      hasNextPage
      startCursor
      endCursor
      hasPreviousPage
    }
    edges {
      cursor
      node {
        id
        title
        author
        duration
        coverURL
        audioURL
        attached
      }
    }
  }
}
