// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: auth.sql

package sqlc

import (
	"context"
)

const deleteRefreshToken = `-- name: DeleteRefreshToken :execrows
DELETE FROM auth_token WHERE refresh_token_id = $1
`

func (q *Queries) DeleteRefreshToken(ctx context.Context, refreshTokenID string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteRefreshToken, refreshTokenID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const saveRefreshToken = `-- name: SaveRefreshToken :exec
INSERT INTO auth_token (refresh_token_id) VALUES ($1)
`

func (q *Queries) SaveRefreshToken(ctx context.Context, refreshTokenID string) error {
	_, err := q.db.Exec(ctx, saveRefreshToken, refreshTokenID)
	return err
}
