// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"database/sql"
	"time"
)

type AuthToken struct {
	ID             sql.NullInt64
	RefreshTokenID string
	CreatedAt      time.Time
}

type Role struct {
	RoleCode   string
	Permission sql.NullString
}

type Soundtrack struct {
	ID          int32
	Title       string
	Author      string
	Duration    int16
	CoverImage  sql.NullString
	AudioFile   string
	IsValidated bool
	CreatorID   int64
	CreatedAt   time.Time
}

type SoundtrackHash struct {
	ID           int64
	Hash         string
	SoundtrackID sql.NullInt32
}

type User struct {
	ID           int64
	FirstName    string
	LastName     sql.NullString
	Username     sql.NullString
	LanguageCode sql.NullString
	UserRole     string
	VisitedAt    time.Time
	CreatedAt    time.Time
}

type UserSoundtrack struct {
	UserID       int64
	SoundtrackID int32
	CreatedAt    time.Time
}
