// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: user.sql

package sqlc

import (
	"context"
)

const attachSoundtrack = `-- name: AttachSoundtrack :exec
INSERT INTO user_soundtrack (user_id, soundtrack_id) VALUES ($1, $2)
`

type AttachSoundtrackParams struct {
	UserID       int64
	SoundtrackID int32
}

func (q *Queries) AttachSoundtrack(ctx context.Context, arg AttachSoundtrackParams) error {
	_, err := q.db.Exec(ctx, attachSoundtrack, arg.UserID, arg.SoundtrackID)
	return err
}
