// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: user.sql

package sqlc

import (
	"context"
)

const attachSoundtrack = `-- name: AttachSoundtrack :exec
INSERT INTO user_soundtrack (user_id, soundtrack_id) VALUES ($1, $2)
`

type AttachSoundtrackParams struct {
	UserID       int64
	SoundtrackID int32
}

func (q *Queries) AttachSoundtrack(ctx context.Context, arg AttachSoundtrackParams) error {
	_, err := q.db.Exec(ctx, attachSoundtrack, arg.UserID, arg.SoundtrackID)
	return err
}

const unattachSoundtrack = `-- name: UnattachSoundtrack :execrows
DELETE FROM user_soundtrack WHERE user_id = $1 AND soundtrack_id = $2
`

type UnattachSoundtrackParams struct {
	UserID       int64
	SoundtrackID int32
}

func (q *Queries) UnattachSoundtrack(ctx context.Context, arg UnattachSoundtrackParams) (int64, error) {
	result, err := q.db.Exec(ctx, unattachSoundtrack, arg.UserID, arg.SoundtrackID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
