// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package models

type SoundtrackResult interface {
	IsSoundtrackResult()
}

type NotFound struct {
	Message string `json:"message"`
}

func (NotFound) IsSoundtrackResult() {}

type Soundtrack struct {
	ID         string `json:"id"`
	Title      string `json:"title"`
	Author     string `json:"author"`
	Duration   int    `json:"duration"`
	CoverImage string `json:"coverImage"`
	FileURL    string `json:"fileURL"`
	CreatorID  string `json:"creatorId"`
	CreatedAt  string `json:"createdAt"`
}

func (Soundtrack) IsSoundtrackResult() {}

type SoundtracksFilter struct {
	Page int `json:"page"`
}

type SoundtracksResponse struct {
	Soundtracks []Soundtrack `json:"soundtracks"`
}
