mutation CreateSoundtrack(
  $title: String!
  $author: String!
  $coverImage: Upload
  $audiofile: Upload!
  $attach: Boolean!
) {
  createSoundtrack(
    input: {
      title: $title
      author: $author
      coverImage: $coverImage
      audiofile: $audiofile
      attach: $attach
    }
  )
}
