mutation CreateSoundtrack(
  $title: String!
  $author: String!
  $coverImage: Upload
  $audiofile: Upload!
) {
  createSoundtrack(
    input: { title: $title, author: $author, coverImage: $coverImage, audiofile: $audiofile }
  )
}
