name: Deploy to Firebase Hosting on merge
"on":
  push:
    branches:
      - main
      - "client/**"
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client
    steps:
      - uses: actions/checkout@v2
      - run: npm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_OASIS_MUSIC_APP }}"
          channelId: live
          projectId: oasis-music-app
